{ pkgs, ... }:
{
  imports = [
    ./packages/zsh.nix
    ./packages/hyprland.nix
    ./packages/steam.nix
    ./packages/ly.nix
    ./packages/gnupg.nix
    ./packages/pcscd.nix
    ./packages/doas.nix
    ./packages/obs.nix
    ./packages/sway.nix
    ./packages/flatpak.nix
  ];

  fonts.packages = with pkgs; [
    corefonts
    liberation_ttf
    dejavu_fonts
  ];

  environment.systemPackages = with pkgs; [
    ghc
    haskellPackages.haskell-language-server
    ormolu
    git
    github-cli
    man-pages
    man-pages-posix
    vesktop
    telegram-desktop
    clang
    clang-tools
    gcc
    hyprpaper
    (python314.withPackages (
      python-pkgs: with python-pkgs; [
        requests
        wxpython
      ]
    ))
    pyrefly
    readline
    rlwrap
    vim
    neovim
    nil
    nixfmt
    zig
    zls
    xmake
    cargo
    rust-analyzer
    rustc
    rustfmt
    clippy
    fastfetch
    zsh
    librewolf
    fuzzel
    thunar
    unzip
    kitty
    zoxide
    raylib
    wget
    brightnessctl
    lua
    cloc
    steam
    gdb
    pavucontrol
    prismlauncher
    zenity
    openssl
    fzf
    mpv
    grim
    slurp
    feh
    bvi
    file
    go
    vulkan-tools
    setxkbmap
    fasm
    qrencode
    zbar
    steam-run
    pnpm
    nodejs
    godotPackages_4_7.godot
    gdtoolkit_4
    gdscript-formatter
    bluetui
    wineWow64Packages.stable
    winetricks
    valgrind
    binwalk
    ghidra-bin
    ly
    llvm
    zstd
    libclang
    lld
    swaybg
    busybox
    fontconfig
    gnupg
    pinentry-curses
    qbittorrent
    wl-clipboard
    ripgrep
    ncdu
    htop
    lldb
    xdg-desktop-portal
    xdg-desktop-portal-wlr
    xdg-desktop-portal-gtk
    vlc
    jdk25
    jdt-language-server
    (gradle-packages.mkGradle {
      version = "9.4.1";
      hash = "sha256-KrKVjyoeURIMMmytbzhRU7sR7pOzwhbF/M6/37t+xss=";
      defaultJava = jdk25;
      updateScriptMajorVersion = "9";
    })
    udev
    marktext
    zip
    pkg-config
    audacity
    gimp
    aseprite
    vital
    lmms
    carla
    yt-dlp
    yt-dlg
    mesa-demos
    libreoffice
  ];
}
